language: cpp
sudo: false
matrix:
  include:
  - os: linux
    compiler: clang
    addons: &1
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - liblapack-dev
        - clang-3.6
        - libhdf5-serial-dev
        - gfortran
    env:
      - CXX_COMPILER='clang++-3.6'
      - PYTHON_VER='3.5'
      - C_COMPILER='clang-3.6'
      - Fortran_COMPILER='gfortran'
      - BUILD_TYPE='release'
      - NAME='clang'
      - VERSION='3.6'

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
  - if [[ "$PYTHON_VER" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda install python=2.7
  - conda create -q -n test-environment python=2.7 cmake
  - conda config --add channels http://conda.anaconda.org/psi4
  - conda install --yes psi4
  - source activate test-environment

#before_script:
# - python -V
# - python -c 'import numpy; print(numpy.version.version)'
# - cd ${TRAVIS_BUILD_DIR}
# - export CXX=${CXX_COMPILER}
# - export CC=${C_COMPILER}
# - export FC=${Fortran_COMPILER}
# - export CTEST_OUTPUT_ON_FAILURE=1
# - ${CXX_COMPILER} --version
# - ${Fortran_COMPILER} --version
# - ${C_COMPILER} --version
# - > 
#     cmake -Bbuild -H. 
#     -DCMAKE_CXX_COMPILER=${CXX_COMPILER} 
#     -DCMAKE_C_COMPILER=${C_COMPILER} 
#     -DCMAKE_BUILD_TYPE=${BUILD_TYPE} 
#     -DCMAKE_PREFIX_PATH=${HOME}/miniconda/envs/p4env
#     -DPYTHON_EXECUTABLE="${HOME}/miniconda/envs/p4env/bin/python"
#     -DENABLE_gdma=ON
#     -DENABLE_PLUGIN_TESTING=ON
#     -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/Install
# - cd build
# - ../.scripts/travis_build.sh
script:
  - psi4 --version
#- python ../.scripts/travis_run_test.py
#- python ../.scripts/travis_print_failing.py

# safelist
branches:
  only:
  - master
  - travis
